on: [push, pull_request]
name: Quality assurance
jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: PHPStan
        uses: "greg0ire/phpstan-ga@v2"
        env:
          REQUIRE_DEV: 'true'
        with:
          args: analyse
